config/routes.rb
Rails.application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'
  
  namespace :backoffice do
    resources :send_mail, only: [:create, :edit]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]    
    resources :diagrams, only: [:index]    
    get 'dashboard',  to: 'dashboard#index'    
  end

  namespace :site do
    get 'home', to:'home#index'    
    get 'search', to: 'search#ads'    
    
    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end
    resources :ads_details, only: [:show, :index]
    resources :categories, only: [:show]
    resources :comments, only: [:create]

  end
  
  get 'dudu', to: 'site/home#index'

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers:{
    sessions: 'members/sessions',
    registrations: 'members/registrations'
    }
  root 'site/home#index'

end

app/controllers/site/ads_details_controller.rb
class Site::AdsDetailsController < SiteController
  
  def show
    @categories = Category.order_by_description
    @ad = Ad.find(params[:id])
    respond_to do |format|
      format.html #views
      format.json {render json: @ad, except: :description}
      format.xml {render xml: @ad}
    end
    
  end
  
end

app/controllers/site/categories_controller.rb
class Site::CategoriesController < SiteController
  def show
    @categories = Category.order_by_description
    @category = Category.friendly.find(params[:id])
    @ads = Ad.by_category(@category, params[:page])
  end
end

app/controllers/site/comments_controller.rb
class Site::CommentsController < ApplicationController
  
  before_action :authenticate_member!
  
  def create
    @comment = Comment.new(comments_params)
    @comment.member = current_member
    
    if (@comment.save)
      redirect_to site_ads_detail_path(@comment.ad_id), notice: "Comentário adicionado!"
    else
      redirect_to site_ads_detail_path(@comment.ad_id), notice: "Erro ao adicionar comentário!"
    end
  end
  
  private
  
  def comments_params
    params.require(:comment).permit(:body, :ad_id)
  end
  
  
  
end

app/controllers/site/home_controller.rb
class Site::HomeController < SiteController
  
  def index
    @categories = Category.order_by_description
    @ads = Ad.descending_order(params[:page])
  end
end

app/controllers/site/profile/ads_controller.rb
class Site::Profile::AdsController < Site::ProfileController
  before_action :set_ad, only: [:edit, :update]
  
  def index
    @ads = Ad.to_the(current_member)
  end
  
  def edit
  end
  
  def update
    if (@ad.update(params_ad))
      redirect_to  site_profile_ads_path, notice: "Atualizado com sucesso"
    else
      render :edit
    end
  end
  
  def new
    @ad = Ad.new
  end
  
  def create
    @ad = Ad.new(params_ad)
    @ad.member = current_member
    
    if (@ad.save)
      redirect_to site_profile_ads_path, notice: "Cadastrado com sucesso" 
    else
      render :new
    end
    
  end
  
  private 
  
  def set_ad
    @ad = Ad.find(params[:id])
  end
  
  def params_ad
    params.require(:ad).permit(:id, :title, :price, :category_id, :description_short, :description_md, :picture)
  end
  
end

app/controllers/site/profile/dashboard_controller.rb
class Site::Profile::DashboardController < Site::ProfileController
  def index
  end
end

app/controllers/site/profile/my_data_controller.rb
class Site::Profile::MyDataController < Site::ProfileController
  before_action :set_profile_member, only: [:edit, :update]
  def edit
           
  end
  
  def update
    if (@profile_member.update(params_profile_member))
      redirect_to  edit_site_profile_my_datum_path(current_member.id), notice: "Perfil atualizado com sucesso"      
    else
      render :edit
    end
  end
  
  private
  
    def set_profile_member
      @profile_member = ProfileMenber.find_or_create_by(member_id: current_member.id) 
    end
  
    def params_profile_member
      params.require(:profile_menber).permit(:first_name, :last_name, :birthdate)
    end
end

app/controllers/site/profile_controller.rb
class Site::ProfileController < SiteController
  layout "profile"
  
  def edit
  end
  
  def update
  end
 
end

app/controllers/site/search_controller.rb
class Site::SearchController < SiteController
  
  def ads
    @categories = Category.order_by_description
    @ads = Ad.search(params[:q], params[:page]) 
  end
  
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout "site" 
  
end
                                                        

app/helpers/site/ads_details_helper.rb
module Site::AdsDetailsHelper
end

app/helpers/site/categories_helper.rb
module Site::CategoriesHelper
end

app/helpers/site/comments_helper.rb
module Site::CommentsHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/profile/ads_helper.rb
module Site::Profile::AdsHelper
end

app/helpers/site/profile/dashboard_helper.rb
module Site::Profile::DashboardHelper
end

app/helpers/site/profile/my_data_helper.rb
module Site::Profile::MyDataHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/views/site/ads_details/_ad.html.erb
<div class="thumbnail">
    <%= image_tag @ad.picture.url(:large), class:"img-responsive" %>
    <div class="caption-full">
        <h4 class="pull-right"><%= humanized_money_with_symbol @ad.price %></h4>
        <h4><%= link_to @ad.title   %></h4>
        <%= @ad.description.html_safe %>
    </div>
    <div class="ratings">
        <p class="pull-right">3 reviews</p>
        <p>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            4.0 stars
        </p>
    </div>
</div>

<div class="well">

    <div class="text-right">
        <a class="btn btn-success">Leave a Review</a>
    </div>

    <hr>

    <div class="row">
        <div class="col-md-12">
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            Anonymous
            <span class="pull-right">10 days ago</span>
            <p>This product was great in terms of quality. I would definitely buy another!</p>
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-md-12">
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            Anonymous
            <span class="pull-right">12 days ago</span>
            <p>I've alredy ordered another one!</p>
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-md-12">
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            Anonymous
            <span class="pull-right">15 days ago</span>
            <p>I've seen some better than this, but not at this price. I definitely recommend this item.</p>
        </div>
    </div>

</div>
           

app/views/site/ads_details/_comments.html.erb
<% @ad.comments.each do |comment| %>
    <div class="row">
        <div class="col-md-12">
            
          <% if (current_member && comment.member.id == current_member.id) %>
            <%= rating_for_user @ad, current_member, 'quality' %>  
          <% end %>
          
          <%= comment.member.name %>
          <span class="pull-right"><%= time_ago_in_words(comment.created_at) %></span>
          <p><%= comment.body %></p>
        </div>
    </div>
    <hr>
<% end %>

app/views/site/ads_details/_comments_modal.html.erb
<!-- Modal -->
<%= form_tag site_comments_path do %>
  <div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Comentário</h4>
        </div>
        <div class="modal-body">
          <%= text_area :comment, :body, class:"form-control", cols: 20, rows: 5 %>
          <%= hidden_field :comment, :ad_id, value: @ad.id %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          <%= submit_tag "Enviar", class:"btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/site/ads_details/_show.html.erb
<div class="thumbnail">
    <%= image_tag @ad.picture.url(:large), class:"img-responsive" %>
    <div class="caption-full">
        <h4 class="pull-right"><%= humanized_money_with_symbol @ad.price %></h4>
        <h4><%= link_to @ad.title   %></h4>
        <%= @ad.description.html_safe %>
    </div>
    
      <div class="ratings" style="padding: 5px">
          <p> <%= rating_for @ad, 'quality' %> </p>            
          <p class="pull-right"><%= @ad.rates("quality").count %> <%= t('labels.reviews') %></p>                      
      </div>
    
</div>

<div class="well">

     <% if member_signed_in? %>
      <div class="text-right">
          <button type="button" class="btn btn-success" data-toggle="modal" data-target="#commentModal">
            <%= t('labels.let_your_comment') %>
          </button>
      </div>
    <% else %>
      <div class="text-right">
          <%= link_to "#{t('labels.login_to_comment')}", new_member_session_path, class:"btn btn-success" %>
      </div>
    <% end %>
  
    <hr>
    
    <%= render partial: "site/ads_details/comments" %>
  
</div>
           
<%= render partial: "site/ads_details/comments_modal" %>

app/views/site/ads_details/show.html.erb
<%= render partial: 'site/ads_details/show' %>