config/routes.rb
Rails.application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'
  
  namespace :backoffice do
    resources :send_mail, only: [:create, :edit]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]    
    resources :diagrams, only: [:index]    
    get 'dashboard',  to: 'dashboard#index'    
  end

  namespace :site do
    get 'home', to:'home#index'    
    get 'search', to: 'search#ads'    
    
    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end
    resources :ads_details, only: [:show, :index]
    resources :categories, only: [:show]
    resources :comments, only: [:create]

  end
  
  get 'dudu', to: 'site/home#index'

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers:{
    sessions: 'members/sessions',
    registrations: 'members/registrations'
    }
  root 'site/home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  include FriendlyId
  friendly_id :description, use: :slugged
  
  has_many :ads
  
  # Validates
  validates_presence_of :description
  
  # Scopes
  scope :order_by_description, -> { order(:description) }
  
  
  
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  after_action :verify_authorized, only: [:new, :destroy]
  after_action :verify_policy_scoped, only: :index
  
  def index
    #@admins = Admin.all
    #@admins = Admin.with_restricted_access
    @admins = policy_scope(Admin)
  end
  
  def new
    @admin = Admin.new
    authorize @admin
  end
  
  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to backoffice_admins_path, notice: "Administrador (#{@admin.email}) salvo com sucesso"
    else
      render :new
    end
  end
  
  def edit
  end
  
  def destroy    
    authorize @admin
    emailAdmin = @admin.email    
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "Administrador (#{emailAdmin}) excluído com sucesso"
    else
      render :index
    end
  end
  
  def update        
    if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to backoffice_admins_path, notice: "Administrador (#{@admin.email}) atualizado com sucesso"
    else
      render :edit
    end
  end
  
  private
  
  def set_admin
    @admin = Admin.find(params[:id])
  end
  
  def params_admin
    
    if password_blank?
      params[:admin].except!(:password, :password_confirmation)      
    end
    
    if @admin.blank?
      params.require(:admin).permit([:name, :email, :role, :password, :password_confirmation])
    else
      params.require(:admin).permit(policy(@admin).permitted_attributes)
    end
        
  end
  
  def password_blank?
    params[:admin][:password].blank? &&
    params[:admin][:password_confirmation].blank?
  end
  
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update]
  
  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = CategoryService.create(params_category)
    
    unless @category.errors.any?
      redirect_to backoffice_categories_path, notice: "Categoria (#{@category.description}) salva com sucesso"
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    
    if @category.update(params_category)
      redirect_to backoffice_categories_path, notice: "Categoria (#{@category.description}) atualizada com sucesso"
    else
      render :edit
    end
  end
  
  private
  
  def set_category
    @category = Category.friendly.find(params[:id])
  end
  
  def params_category
    params.require(:category).permit(:description)
  end
  
end

app/controllers/backoffice/categories_controller/category_service.rb
class Backoffice::CategoriesController::CategoryService
  attr_accessor :category

  def self.create(params_category)
    @category = Category.new(params_category)    
    if @category.valid?
      @category.save!
    end      
     @category    
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  
  def index
  end
end

app/controllers/backoffice/diagrams_controller.rb
class Backoffice::DiagramsController < BackofficeController

  def index
    %x(bundle exec erd --filename='public/diagram')    
  end
  
end

app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController
  
  def edit
    @admin = Admin.find(params[:id])
    respond_to do |format|
      format.js
    end
  end
  
  def create
    begin
      AdminMailer.notify_admin(params[:'recipient-name'], params[:'subject-text'], params[:'message-text']).deliver_now
      @notify_message = I18n.t('messages.email_delivered')
      @notify_flag = 'success'
    rescue
      @notify_message = I18n.t('messages.email_not_delivered')
      @notify_flag = 'error'
    end
    
    respond_to do |format|
      format.js
    end
    
  end
   
  
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"
  
  def pundit_user
    current_admin #overide current_user
  end
  
end
                                                        

app/controllers/site/categories_controller.rb
class Site::CategoriesController < SiteController
  def show
    @categories = Category.order_by_description
    @category = Category.friendly.find(params[:id])
    @ads = Ad.by_category(@category, params[:page])
  end
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  
  OptionsForRoles = Struct.new(:id, :description)  
  
  options = []
  
  def options_for_roles
    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)
    end
  end
end
    

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/diagrams_helper.rb
module Backoffice::DiagramsHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/helpers/site/categories_helper.rb
module Site::CategoriesHelper
end

app/views/backoffice/categories/edit.html.erb
<%= render partial: "backoffice/categories/shared/form",
            locals: {action: t('messages.edit', model: @category.model_name.human)} %>

app/views/backoffice/categories/index.html.erb
       
<h1 class="page-header"><%= "#{@categories.model.model_name.human(count: @categories.count)}" %></h1>

<div class="panel panel-default">
  <div class="panel-heading">
      <%= "#{@categories.model.model_name.human(count: @categories.count)}" %>
      <%= link_to new_backoffice_category_path, class: "btn btn-primary btn-circle  pull-right", style: "margin-top: -5px" do %>
          <i class="fa fa-plus"></i>
      <% end %>
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
              <th>#</th>
              <th><%= @categories.model.human_attribute_name("description") %></th>                                            
              <th></th>                                            
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |cat| %>
            <tr>
                <td><%= cat.id %></td>
                <td><%= cat.description %></td>
                <td style="width: 150px">
                  <%= link_to edit_backoffice_category_path(cat.id), class: "btn btn-primary btn-circle" do %>
                      <i class="fa fa-edit"></i>
                  <% end %>
                  <button type="button" disabled="disabled" class="btn btn-danger btn-circle">
                      <i class="fa fa-minus"></i>
                  </button>
                </td>
            </tr>                      
          <% end %>
        </tbody>
      </table>
    </div>
      <!-- /.table-responsive -->
  </div>
<!-- /.panel-body -->
</div>
                    

app/views/backoffice/categories/new.html.erb
<%= render partial: "backoffice/categories/shared/form",
             locals: {action: t('messages.new', model: @category.model_name.human)} %>